version: '3'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "play-move.application:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/play-move-app'
    ports:
      - '8000:8000'
